### ISSUE TITLE
Array growing using ArrayCopy

### ISSUE THREAD

**Issue by DivineDominion** [Sodaware/pangolin.mod#2]
Just discovered your code to familiarize myself with non-trivial bmax patterns 👍

I just discovered your `EventHandlerBag#_grow` method:
https://github.com/Sodaware/pangolin.mod/blob/7938b6f5c6ab512c1e373aa0a74d71f0a5ea3924/events.mod/src/event_handler_bag.bmx#L337

One thing I implemented last week was a mutable array class that auto-grows when you append elements. bmax-ng's generics fail my all the time, so the resulting code works with plain `Object`s only, too. I stumbled across `ArrayCopy` and replaced my for-eachin loops with that.

I don't know how to whip up performance tests, yet, so this might not improve anything. But if it does, replace

```
		For Local pos:Int = 0 To oldObjects.Length - 1
			Self._objects[pos] = oldObjects[pos]
		Next
```

with:

```
		ArrayCopy(oldObjects, 0, Self._objects, 0, oldObjects.Length)
```

(Note you don't have to -1 here because it's not the index, but the length itself we need.)

**Comment by Sodaware** [comment]
Thank you for the tip about `ArrayCopy` - it led me down quite a rabbit hole!

I wrote a [quick performance test](https://gist.github.com/Sodaware/2a4a5ae46d45d0f64a8e50af7c260623) to compare `ArrayCopy` against copying elements using a `For...Next` loop. It's probably not that accurate, but the results were encouraging.

Time to copy a 1,000 element array 1,000,000 times:

| Method               | Time (millisecs) |
|----------------------|-----------------:|
| Copy (For...Next)        | 2249             |
| ArrayCopy            | 1127             |
| Object Copy (For...Next) | 3264             |
| Object ArrayCopy     | 2152             |

For simple Integer arrays, `ArrayCopy` is about twice as fast as copying using a `For...Next` loop. Copying objects is slower, but still shows a good speed improvement. Nice!

But I wondered if there was a better way implement `_grow`. I did some searching and found BlitzMax has built-in functionality for [copying and resizing arrays using "slices"](https://blitzmax.org/docs/en/language/arrays/#copying-an-array).

So instead of creating a larger array and copying the contents, resizing can be done in a single command:

```blitzmax
Local myArray:Int[10]

' Resize array to be 20 elements.
myArray = myArray[..20]
```

Using slices reduces the `_grow` method to this:

```blitzmax
Method _grow(newCapacity:Int = -1)
	' Use default new size if none set.
	If newCapacity < 0 Then newCapacity = ((Self._objects.Length * 3) / 2) + 1

	' Resize the array.
        Self._objects = Self._objects[..newCapacity]
End Method
```

A [quick performance test](https://gist.github.com/Sodaware/ed1151972c586a6b62facbe986de2fef) gave the following results for adding 10,000 items to a bag 10,000 times:

| Method               | Time (millisecs) |
|----------------------|-----------------:|
| Original `_grow`        | 821             |
| ArrayCopy `_grow`        | 559             |
| Slices `_grow`            | 482             |

`ArrayCopy` is a big improvement, but slices are even faster (and work with vanilla BlitzMax too). I'm very pleased with the improvement, and I learnt some new things about BlitzMax too.

Thank you!

**Comment by DivineDominion** [comment]
Good to know about the speed comparisons! (Since googling for anything bmax produces scant results, you might want to consider publishing these findings as a post somewhere :)) I switched my implementation to slices as well. Works fine!

**Comment by Sodaware** [comment]
Glad it all worked out! I wrote up the array notes here: http://sodaware.sdf.org/blog/blitzmax-optimization-arrays/

I don't write on the site all that often, but all my BlitzMax notes go there.

**Comment by DivineDominion** [comment]
Great! I did spread it on the German blitzforum.de :)
